### ISSUE TITLE
Would be useful to have a parameter to strip spaces for comparison

### ISSUE THREAD

**Issue by behanjc** [capitalone/datacompy#15]
As probably expected, the following code will return a mismatch since 'B'<>'B ':
```
import pandas as pd
import datacompy

df1 = pd.DataFrame([
        {'id': 1234, 'column_value': 'A'},
        {'id': 2345, 'column_value': 'B'}])

df2 = pd.DataFrame([
        {'id': 1234, 'column_value': 'A'},
        {'id': 2345, 'column_value': 'B '}])

compare = datacompy.Compare(
    df1,
    df2,
    join_columns='id',
    abs_tol=0,
    rel_tol=0,
    )
compare.matches(ignore_extra_columns=False)
# False

# This method prints out a human-readable report summarizing and sampling differences
print(compare.report())
```
What I propose is an optional parameter to ignore differences where the only difference is leading or trailing spaces. In this example it is obvious that there is a trailing space. However, when we are dealing with extracts from different databases/source files, without real control over the ETL of these, sometimes we can't prevent these discrepancies. We may wish to ignore these types of mismatches to identify 'worse' mismatches more effectively.

Another candidate could be ignoring case sensitivity differences.
Of course these could both be easily handled with preprocessing the dataframes, but still could be some convenient enhancements!

**Comment by SanthiSridharan** [comment]
This is a great suggestion. I think that we can achieve this by 
a. having a data_cleansing function for various options - change all to a single case, remove all trailing spaces, ignore all whitespaces.... 
b. have a new compare with options function rather than modifying the existing compare function
c. this compare with option function can take the options to cleanse - perform the cleansing operations and then call the compare function to spit out the results based on the cleansed data frames.
