### ISSUE TITLE
Regression in Pandas is causing tests to fail?

### ISSUE THREAD

**Issue by fdosani** [capitalone/datacompy#19]
Seems like the unit tests are failing due to a potential regression in Pandas?
https://github.com/pandas-dev/pandas/issues/21119

```python
def test_decimal_with_joins():
    df1 = pd.DataFrame([{'a': Decimal('1'), 'b': 2}, {'a': Decimal('2'), 'b': 2}])
    df2 = pd.DataFrame([{'a': 1, 'b': 2}, {'a': 2, 'b': 2}])
    compare = datacompy.Compare(df1, df2, 'a')
    assert compare.matches()
    assert compare.all_columns_match()
    assert compare.all_rows_overlap()
    assert compare.intersect_rows_match()
```

Following test raises: `ValueError: You are trying to merge on object and int64 columns. If you wish to proceed you should use pd.concat`

Would it make sense to pin the Pandas version?

**Comment by theianrobertson** [comment]
Hmm, yeah confirmed that I'm seeing that behaviour with Pandas 0.23.0.  Had only been using 0.20.3 before since that was the last in the main conda channel :grin:

I'd been trying to keep the comparisons "smart", where if it was the same values stored as different types (e.g. `int64 1` and `Decimal('1')` they'd still match.  Maybe in the case of the join keys it makes sense to force them to be the same type, and keep the "smart" behaviour on the compare fields.  

For pinning version, what do you think of just specifying a range in the docs and outside the range of versions is "use at your own risk".  Since this is a utility I'd assume most environments would have other Pandas requirements so I don't want to be too restrictive.

There's another warning of something that'll break in a future Pandas release when I run on 0.23.0 so I'll throw that into its own issue.
