### ISSUE TITLE
who can help make the result significantly

### ISSUE THREAD

**Issue by swloveydp** [capitalone/datacompy#255]
i use the datacompy.Compare compare two data frame and write the intersect_rows two excle  i want the result in excle significantly such as the flow picture who can help 
![image](https://github.com/capitalone/datacompy/assets/16555783/480a0563-594b-4c93-a7d1-8a6be03b86b2)

**Comment by fdosani** [comment]
Hey @swloveydp Just for my own understanding an clarity you want to be able to export your results to excel? Is that right?
If that is the case you can just export `intersect_rows` to excel with something like this:

```python
type(compare.intersect_rows)
> pandas.core.frame.DataFrame

compare.intersect_rows.to_excel(....)
```

Since `intersect_rows` is just a Pandas DataFrame, Pandas has a Excel writer you can see here: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html#pandas-dataframe-to-excel

**Comment by fdosani** [comment]
@swloveydp did the above solve your situation? Feel free to reopen the issue if not, closing for now.
