### ISSUE TITLE
Abstract base class for native Compare functionality

### ISSUE THREAD

**Issue by fdosani** [capitalone/datacompy#260]
@ak-gupta @jdawang @NikhilJArora @goodwanghan 
Just want to get some opinions and agreement on aligning to some abstract base class for our native implementations. 

I think this is already implemented here so the lift is minimal: https://github.com/capitalone/datacompy/blob/koalas-refactor/datacompy/base.py

This will set us up for dealing with the native SparkCompare too in the future for cleaning that up.

**Comment by fdosani** [comment]
Part of this I think it also makes sense to rename the `Compare` class -> `PandasCompare`, along with `core.py` -> `pandas.py`

**Comment by goodwanghan** [comment]
I was experimenting on this PR https://github.com/capitalone/datacompy/pull/259
The original goal was to test duckdb performance (it is amazing). And then I started to rethink about the datacompy design.

The design ideas in this PR are:

1. The user interface should be functional, they don't learn any new class, instead just a few simple functions that can be used independently
2. We unify the compare results, instead of the compute process. I feel the compute processes of different backends may need totally different structures to keep good performance, so may be impossible to unify.
3. We can separate preprocess (dedup,. lower col names, strip string values etc.), schema compare, data compare and report. The original interface is packed but not really flexible. For example, whether to dedup and how to dedup needs more options.

**Comment by fdosani** [comment]
Closing this. Implemented in #258
