### ISSUE TITLE
It seems `SparkCompare` object has no attribute 'sample_mismatch` ?

### ISSUE THREAD

**Issue by pangjac** [capitalone/datacompy#283]
Hi,

I am currently using 0.8.4. For a certain column, I am trying to print a sample_mismatch to check what is the value different for this column between two pyspark dataframe : It seems `SparkCompare` object has no attribute 'sample_mismatch` ?
![image](https://github.com/capitalone/datacompy/assets/13987136/17b0f2b6-4c40-4ed8-a1c9-056f3e447479)

Wondering if this is the version issue or not. However, the latest [documentation](https://capitalone.github.io/datacompy/api/modules.html) does not list `sample_mismatch` in [datacompy.spark module](https://capitalone.github.io/datacompy/api/datacompy.html#module-datacompy.spark) as well. 

If confirmed, could you provide a quick poke on the reason why this method is not inherited. **If this is no specific blockers, I'd happy to contribute to dev this method under spark module.**

Thanks for this wonderful package!

**Comment by fdosani** [comment]
Hey @pangjac first off thank you for supporting the package!

`sample_mismatch` doesn't exist for the `SparkCompare` class in that version of `datacompy`. We have a branch which is waiting review where we are shifting to pandas on pyspark if you are ok using that instead. `v0.8.4` is fairly old so I'd highly recommend bumping up if you are able to.

If you look at the new implementation (which aligns better to the pandas, polars, and fugue logic) [we will have that function](https://github.com/capitalone/datacompy/blob/pandas-on-spark-refactor/datacompy/spark.py#L486) natively for Spark.

Alternatively I wonder if the internal dataframe: `_all_rows_mismatched` would give you what you need. you can filter on the column you are interested in since its just a Spark DF.

**Comment by fdosani** [comment]
@pangjac Just wanted to follow up and see if this was solved for you? Thanks!
