### ISSUE TITLE
pandas df with datetime.date cols returns false differences if ignore_case=True

### ISSUE THREAD

**Issue by sundeep-longledge** [capitalone/datacompy#327]
When ignore_case=True, identical values with type datetime.date will be reported as unequal.
This happens because in core.py/columns_equal() the attempt to call str.upper() on the col for case insensitive-comparison will throw an exception. The try/except returns false for any caught exception.

```
import pandas as pd
import datacompy
import datetime

df1 = pd.DataFrame([{'date_field':datetime.date(2024,5,8)}])
df2=df1.copy()

print("incorrectly reports unequal")                            
results = datacompy.Compare(df1=df1,df2=df2,on_index=True, ignore_case=True)
print(results.report())

results = datacompy.Compare(df1=df1,df2=df2,on_index=True, ignore_case=False)
print("Works correctly")                            
print(results.report())
```

**Comment by fdosani** [comment]
So it seems to be an issue of `datetime.date `vs `datetime.datetime`. date returns an `O` (object) vs datetime which returns a type of `M`. We could just convert all objects to "strings" and then compare, but I'm sure that will break something else.

**Comment by divithraju** [comment]
Hi [@fdosani ],

 I understand that the issue arises because `datetime.date` returns an object type 'O', while `datetime.datetime` returns a type 'M'. Applying `str.upper()` to non-string types like `datetime.date` throws an exception, leading to the incorrect comparison.

### Proposed Solution:
To resolve this issue, I propose updating the `columns_equal()` function in `core.py` to handle non-string types more gracefully. Here’s the approach:

1. **Check if the column values are strings** before applying `str.upper()`:
   - If the values are of type `str`, apply the case-insensitive comparison using `upper()`.
   - If the values are of another type (e.g., `datetime.date`), fall back to the default equality comparison without case sensitivity.

### Example of How It Could Be Implemented:

```python
def columns_equal(col1, col2, ignore_case=False):
    try:
        # Apply case-insensitive comparison for strings only
        if isinstance(col1, str) and isinstance(col2, str) and ignore_case:
            return col1.upper() == col2.upper()
        else:
            return col1 == col2
    except Exception as e:
        # Log the error if needed, and return False
        return False

**Comment by fdosani** [comment]
@divithraju Sorry for the delay and appreciate the effort here. I don't think you can check `isinstance(col1, str)` since you are checking the column which is of type:` pandas.core.series.Series`. It will never equate to true. I have a fix in the works for this.

**Comment by fdosani** [comment]
@ak-gupta @jdawang Want to get your thoughts here on a specific proposal. The main issue is with Pandas you can have mix typing with object columns. This can lead to really funky situations. 

I think we should stop supporting mixed typing. Especially with arrow becoming the standard it is something which will be a thing moving forward even with Pandas if and when they make a full switch over. Ideally we can just not support mixed types and if it is mixed we just return a default `False`. Are you both OK with this?

Here is a PR with the actual proposal: https://github.com/capitalone/datacompy/pull/335

**Comment by fdosani** [comment]
No need for a PR I've already put one up in as referenced above.
