### ISSUE TITLE
Check out pytest-spark for spark tests

### ISSUE THREAD

**Issue by theianrobertson** [capitalone/datacompy#39]
https://github.com/malexer/pytest-spark

Could get spark tests up and running on Travis then maybe?

**Comment by theianrobertson** [comment]
@fdosani I saw you mention this elsewhere - wouldn't mind picking your brain sometime if you dig into it

**Comment by fdosani** [comment]
Sound good, it looks neat and can help simplify testing spark apps which might be a bit cumbersome to begin with.

**Comment by theianrobertson** [comment]
yep - I've had some weird bugs with spark environments and testing, so would be nice if it simplifies :)

**Comment by dan-coates** [comment]
As it turns out, my team is creating a Spark Python library right now and we spent a fair amount of time digging into how pyspark runs their own tests. :)

I'm curious as to what the difficulty is running Spark tests on Travis since I've never tried it. If the issue is just finding `pyspark` to import it, I don't think a plugin is needed for it. The Spark tests here also already create a SparkSession fixture to be used once for all tests.

**Comment by dan-coates** [comment]
@theianrobertson We've gotten pytest working for our project without any special stuff - just `pip install pyspark pytest` basically. I think it'll come down to what the Travis environment is like and what kind of restrictions it puts on you. Another approach we're moving towards is building a Docker image with the test environment in place so that it's always consistent wherever you run it.

Let me know if you'd like me to look into this for this project. Not sure what sort of access/permissions I'd need to fool around with it.

**Comment by fdosani** [comment]
I think for testing things in datacompy we would want to go the docker route if that makes sense, will need to dig into Travis a bit more to see what support they offer.

**Comment by theianrobertson** [comment]
As per #40 I've got the spark tests running on Travis, and did swap over to pytest spark (not that it's totally required, but swapped anyway).  Will be doing a major version bump when that gets merged to master.
